[package]
name = "tabu_structure"
version = "0.1.0"
edition = "2021"

[lib]
name = "tabu_structure"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.22.3"
features = ["extension-module"]

[profile.release]
opt-level = 3